# Generated by Django 4.1 on 2022-10-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(default="events/default.png", upload_to="events/"),
        ),
    ]
