# Generated by Django 4.1 on 2022-10-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
