# Generated by Django 4.1 on 2022-10-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumni", "0013_alumni_graduation_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="company",
            field=models.CharField(default="No company", max_length=100),
        ),
    ]
