# Generated by Django 4.1 on 2022-10-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumni", "0015_alter_alumni_company_alter_alumni_job_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="company",
            field=models.CharField(default="No company", max_length=100),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="job_profile",
            field=models.CharField(default="Not Working", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="last_name",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="profile_image",
            field=models.ImageField(default="users/default.png", upload_to="users/"),
        ),
    ]
